//
//  ConverterModels.swift
//  CurrencyConverter
//
//  Created by Apple on 12/01/18.
//  Copyright (c) 2018 Apple. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Converter
{
  // MARK: Use cases
  
  enum ExchangeRate
  {
    struct Request
    {
        static let hasArrayResponse = "HasArrayResponse"
        
        var urlPath: String
        var requestType: NSInteger
        var fileData: Data
        var dataFilename: String
        var fileName: String
        var mimeType: String
        var headers: [String: String]?
        var parameters: Dictionary<String, Any>
        
        override init() {
            urlPath = ""
            requestType = 0
            fileData = Data()
            dataFilename = ""
            fileName = ""
            mimeType = ""
            parameters = [:]
            super.init()
        }
        
        public func getParams() -> Dictionary<String, Any> {
            return parameters
        }
        
        public static func getUrl(path: String) -> String {
            let client: NetworkHttpClient = NetworkHttpClient.sharedInstance
            return String.init(format: "%@%@",client.urlPathSubstring, path)
        }
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
