//
//  ConverterPresenter.swift
//  CurrencyConverter
//
//  Created by Apple on 12/01/18.
//  Copyright (c) 2018 Apple. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConverterPresentationLogic
{
  func presentExchangeRate(response: Converter.ExchangeRate.Response)
}

class ConverterPresenter: ConverterPresentationLogic
{
  weak var viewController: ConverterDisplayLogic?
  
  // MARK: Do ExchangeRate
  
  func presentExchangeRate(response: Converter.ExchangeRate.Response)
  {
    let viewModel = Converter.ExchangeRate.ViewModel()
    viewController?.displayExchangeRate(viewModel: viewModel)
  }
}
